### ISSUE TITLE
[SUGGESTION] Farmers Delight compat

### ISSUE THREAD

**Issue by Sunconure11** [cflip/GrillinGalore#1]
Farmers Delight, for starters, adds quite a few food items. It also adds it's own onion crop. Would it be possible to have various forms of cross-compat between the two?

**Comment by cflip** [comment]
Should be possible! I will look into this.

**Comment by Sunconure11** [comment]
The addon Expanded Delights also adds some stuff that might be worth looking into

**Comment by cflip** [comment]
I've added a common item tag for onions so crafting recipes from other mods that use these tags should be compatible. Looks like Farmer's Delight is still working on this functionality too:
https://github.com/newhoryzon/farmers-delight-fabric/issues/18

**Comment by Sunconure11** [comment]
Would it be possible to also add options to turn off drops of your onion crops? Solely so we do not have duplicate items doing the same things.

**Comment by cflip** [comment]
I can add a config feature that disables Grillin' Galore onion drops, but it might be nice if the mod had support for some kind of unification system that ensures that there is only one onion item in the game. I've seen these for ores in Forge modpacks, but I'm not sure what options there are for Fabric or if this is the best solution.

**Comment by Sunconure11** [comment]
Closest you get on Fabric are tags

**Comment by Sunconure11** [comment]
I'd say talk with the devs of Farmers Delight though, for how to pull this off properly.
