### ISSUE TITLE
[SUGGESTION] Better Animals Plus support

### ISSUE THREAD

**Issue by Sunconure11** [cflip/GrillinGalore#2]
BA+ adds a few mobs like boar and what not that would benefit from this. Maybe some special drops from their mobs if both mods are installed?

**Comment by cflip** [comment]
I think it would be good if the boars had a chance of dropping ribs as well.

**Comment by Sunconure11** [comment]
@cflip Heads up, but 1.19.2 has dropped.

**Comment by cflip** [comment]
It looks like the boars from that mod use the pig loot table. I checked in singleplayer and they already drop ribs occasionally.
